In [1]:

import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
41   23    Male     Good        PG       Yes
29   83  Female  Average        UG       Yes
5    31  Female  Average    School       Yes
7    60  Female     Poor    School       Yes
26   53  Female     Poor        PG        No

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
from sklearn.model_selection import train_test_split


X = df[['review', 'education']]
y = df['purchased']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train

     review education
16     Poor        UG
13  Average    School
47     Good        PG
27     Poor        PG
2      Good        PG
40     Good    School
42     Good        PG
21  Average        PG
31     Poor    School
36     Good        UG
10     Good        UG
37  Average        PG
7      Poor    School
22     Poor        PG
34  Average    School
39     Poor        PG
19     Poor        PG
14     Poor        PG
6      Good    School
15     Poor        UG
9      Good        UG
33     Good        PG
11     Good        UG
43     Poor        PG
46     Poor        PG
30  Average        UG
32  Average        UG
0   Average    School
4   Average        UG
1      Poor        UG
41     Good        PG
23     Good    School
25     Good    School
29  Average        UG
49     Good        UG
28     Poor    School
5   Average    School
44  Average        UG
3      Good        PG
17     Poor        UG

In [9]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])